### PR TITLE
Added maxValueSize to allow configuration of the value size to allow

### PR DESCRIPTION
**Pull request by luislobo**
Memcache can now be configured on how big is the value to be stored, so, this should be configurable. We are using right now a 10MB size.

### CODE REVIEW

**Comment by luislobo** [comment]
@victorquinn whenever you can, could you check this PR? Thanks!

**Comment by victorquinn** [comment]
Looks great, thanks!

Apologies on the long response, I somehow wasn't subscribed to notifications for this repo so your mentioning me was the first message I actually got about it.

I'll push this to npm and update here.

**Comment by victorquinn** [comment]
Ok, this is deployed to npm as 0.2.4!

**Comment by victorquinn** [comment]
Ahhh whoops ignore my comment which referenced this PR, meant to reference #10 which broke callbacks, sorry!

**Pull request merged**
